server:
  port: 8888
  undertow:
    accesslog:
      dir: ./log
      enabled: true
      pattern: common
      prefix: access_log
      suffix: log
    buffer-size: 1024
    direct-buffers: true

spring:
  application:
    name: SpringRBAC
  datasource:
    url: jdbc:mysql://192.168.1.5:3306/spring_rbac2?useSSL=false&serverTimezone=UTC
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      connection-test-query: SELECT 1

